### PR TITLE
global: bump invenio-search-ui version

### PR DESCRIPTION
**Pull request by ntarocco**

### CODE REVIEW

**Comment by ntarocco** [comment]
@drjova added release information. Please double check if they are ok!

**Comment by ntarocco** [comment]
@drjova fixed as discussed

**Comment by drjova** [comment]
@ntarocco could you please make the version bump in a separate commit like this one https://github.com/inveniosoftware/invenio-search-ui/commit/150487ff95e82dd70965fee3bdf52f6d7574a192 :) thanks

**Comment by ntarocco** [comment]
@drjova done, 2 commits! Let me know if now it is ok!

**Comment by lnielsen** [comment]
I've tried to restart the build, but I'm not really sure why it fails.

**Comment by ntarocco** [comment]
@drjova I have updated `invenio-search-js` to version 1.3.1. To be checked when we release 1.3.1 of `invenio-search-js` on npm.
See: https://github.com/inveniosoftware/invenio-search-js/pull/105

**Comment by drjova** [comment]
@ntarocco ```invenio-search-js``` ``v1.3.1`` has been release, waiting to show up in npm )

**Comment by ntarocco** [comment]
blocked by: https://github.com/PyCQA/pydocstyle/issues/289

**Comment by FarmerSez** [comment]
Hey @ntarocco, `pydocstyle-2.1.1` was released 👍

**Comment by ntarocco** [comment]
@drjova and @drjova Travis is now happy, you can merge + release.
The issue was that Travis was running this build on Ubuntu 14, which was installing ElasticSearch 5.5. (while the branch master on Ubuntu 12 with ES 1.4).
I fixed by installing the right version of ES. Troubleshoot created here: https://github.com/inveniosoftware/troubleshooting/issues/24
I have also updated the Pypi deploy user/psw.

**Pull request merged**
